"""DB: Init

Revision ID: e799e433fc99
Revises: 
Create Date: 2024-09-04 20:16:50.143808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e799e433fc99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=1000), nullable=False),
    sa.Column('panggilan', sa.String(length=1000), nullable=True),
    sa.Column('kelas', sa.String(length=100), nullable=False),
    sa.Column('nomor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    # ### end Alembic commands ###
